root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/main ./cmd/server"
bin = "tmp/main"

include_dir = ["cmd", "internal", "config", "database"]
include_ext = ["go", "mod", "sum", "yml", "yaml", "tpl", "tmpl", "html"]

exclude_dir = ["tmp", "vendor", ".git", "migrations", "schema", "scripts"]
exclude_regex = ["_test\\.go$"]

delay = 500
stop_on_error = true
poll = true

[log]
time = true
main_only = false
silent = false

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true
